Added parent attribute and toggle click emit
owowagency/bootstrap-vue pull request #27
Opened 2022-01-14 14:43 UTC by TimDirks

2022-01-14 15:51 UTC, barisbora approved these changes

2022-01-14 15:51 UTC, barisbora commented on src/components/Collapse/Collapse.vue
> +const emit = defineEmits(['click:toggle']);
```suggestion
const emit = defineEmits<{(event: 'click:toggle'): void}>();
```

2022-01-17 11:26 UTC, thomasowow requested changes
Your commit messages will not result in new versions to be released.
Read this: https://github.com/semantic-release/semantic-release#commit-message-format

2022-01-17 11:26 UTC, thomasowow commented on src/components/Collapse/Collapse.test.ts
> +        expect(wrapper.emitted('click:toggle')).toBeTruthy();
This test will never ever fail. It is like giving the answers of a test to a student. You need to test that the `click` event is resulting in the `click:toggle` event.

2022-01-17 11:26 UTC, thomasowow commented on src/components/Collapse/Collapse.vue
> +        @click="clickToggle"
```suggestion
        @click="emit('click:toggle')"
```

2022-01-18 12:25 UTC, thomasowow approved these changes

2022-01-19 10:35 UTC, merged