Added slot around menu items
owowagency/bootstrap-vue pull request #28
Opened 2022-01-14 14:54 UTC by TimDirks

2022-01-14 15:57 UTC, barisbora approved these changes

2022-01-14 15:57 UTC, barisbora commented on src/components/DropdownMenu/DropdownMenu.vue
> +        <slot name="items">
```suggestion
        <slot name="items" :click="clickItem">
```
I think we should pass the click event also so we can trigger click from custom dropdown item

2022-01-17 11:29 UTC, thomasowow requested changes

2022-01-17 11:29 UTC, thomasowow commented on src/components/DropdownMenu/DropdownMenu.vue
> +                :key="`item-${index}`"
We could even prevent the parent having to do the loop.
```suggestion
        <slot name="items">
            <template v-for="(item, index) of items">
                <slot name="item" :item="item">
```

2022-01-17 11:29 UTC, thomasowow commented on src/components/DropdownMenu/DropdownMenu.vue
> +        <slot name="items">
```suggestion
        <slot name="items" :items="items">
```

2022-01-18 12:30 UTC, thomasowow approved these changes

2022-01-18 12:30 UTC, thomasowow commented on src/components/Dropdown/Dropdown.vue
> +            </template>
I think I would not be able to do the following:
```
<Dropdown>
    <template #item="{item}">
        {{ item.label }}
```
I think this also applies to `FormDropdown`. Can we have a nice eligant and flexible way to pass these slots to children?

2022-01-20 12:13 UTC, thomasowow approved these changes

2022-01-27 07:15 UTC, merged