Feature/dropdown slot for menu
owowagency/bootstrap-vue pull request #29
Opened 2022-01-14 15:00 UTC by TimDirks

Based on #28 

See [diff here](url)

2022-01-17 07:54 UTC, barisbora approved these changes

2022-01-17 11:31 UTC, thomasowow requested changes

2022-01-17 11:31 UTC, thomasowow commented on src/components/Dropdown/Dropdown.vue
> +        <slot name="dropdownMenu">
Or more properties
```suggestion
        <slot name="dropdownMenu" :items="items">
```

2022-01-18 12:32 UTC, thomasowow approved these changes

2022-01-19 10:35 UTC, merged